#timestamp:20250718033746560410014
services:
  ultra-coins-hottate:
    image: ghcr.io/ultra-coins/ultra-coins-hottate/hottate:main
    container_name: ultra-coins-hottate
    labels:
      traefik.enable: true
      traefik.http.routers.ultra-coins-hottate.priority: 2
      traefik.http.routers.ultra-coins-hottate.rule: "Host(`ultra.coins.tsukuba.ac.jp`) && PathPrefix(`/hottate`)"
      traefik.http.services.ultra-coins-hottate.loadbalancer.server.port: 80
      traefik.http.routers.ultra-coins-hottate.entrypoints: websecure
      traefik.http.routers.ultra-coins-hottate.tls: true
      #* Remove prefix from /hottate to /
      # create a middleware named `remove-prefix`
      traefik.http.middlewares.remove-prefix.stripprefix.prefixes: /hottate
      # apply the middleware named `remove-prefix`
      traefik.http.routers.ultra-coins-hottate.middlewares: remove-prefix@docker
    networks:
      - traefik

networks:
  traefik:
    external: true
