#timestamp:20250703173754355177009
services:
  ultra-coins-hottate:
    image: ghcr.io/ultra-coins/ultra-coins-hottate/hottate:main
    container_name: ultra-coins-hottate
    labels:
      traefik.enable: true
      traefik.http.routers.ultra-coins-website.rule: Host(`hottate.ultra.coins.tsukuba.ac.jp`)
      traefik.http.services.ultra-coins-website.loadbalancer.server.port: 80
      traefik.http.routers.ultra-coins-website.entrypoints: websecure
      traefik.http.routers.ultra-coins-website.tls: true
    networks:
      - traefik

networks:
  traefik:
    external: true